---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This website is to track my reading on the book Pattern Recognition and Machine Learning by Christopher M. Bishop.

**Chapter 1: Introduction**

+ [1.1 Example: Polynomial Curve Fitting](1_1.html)

+ [1.2 Probability Theory](1_2.html)

+ [1.6 Information Theory](1_6.html)

**Chapter 2: Probability Distribution**

+ [2.3 The Gaussian Distribution](2_3.html)

+ [2.4 The Exponential Family](2_4.html)

+ [2.5 Nonparametric methods](2_5.html)


**Chapter 3: Linear Models for Regression**

+ [3.1 Linear Basis Function Models](3_1.html)

+ [3.3 Bayesian Linear Regression](3_3.html)

+ [3.4 Bayesian Model Comparison](3_4.html)

+ [3.5 The Evidence Approximation (Naive Bayes)](3_5.html)

[Note 1: write regression function on p95 when reading regression!!]

[Note2: Unsurprisingly, the least squares approach to regression does not exhibit robustness, because it corresponds to maximum likelihood under a (conditional) Gaussian distribution.]


**Chapter 4: Linear Models for Classification**

+ [4.1 Discriminant Functions](4_1.html)

+ [4.2 Probabilistic Generative Models](4_2.html)

+ [4.3 Probabilistic Discriminative Models](4_3.html)

+ [4.4 - 4.5 The Laplace Approximation](4_4.html)


**Chapter 5: Neural Networks**

+ [5.1 Feed-forward Network Functions](5_1.html)

+ [5.2 Network Training](5_2.html)

+ [5.3 Error Backpropagation](5_3.html)









